name: Reveal Secret Spaced
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Print spaced secret
        run: |
          echo "${{ secrets.CDK_PARAM_WHATSAPP_WEBHOOK_VERIFY_TOKEN }}" | sed 's/./& /g'
